config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root 'posts#index'
  resources :posts do
 	resources:responds
	end
 namespace :account do
	resource :posts
	resource :responds
end

end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :description, :presence =>true
	has_many :responds , dependent: :destroy
	belongs_to :owner , class_name:"User" , foreign_key: :user_id, counter_cache: :posts_count 
	belongs_to :owner , class_name:"User" , foreign_key: :user_name 
	def editable_by?(user)
	   user && user == owner
	end
end

app/models/respond.rb
class Respond < ActiveRecord::Base
	belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :posts
	has_many :responds
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/account/responds_helper.rb
module Account::RespondsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/responds_helper.rb
module RespondsHelper
end

app/views/common/_header.html.erb
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Twitter</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"  crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="twitter.css">

app/views/common/_hot.html.erb
<div class="panel panel-default">

  <div class="panel-body">

   熱門

   <ul class="hot">

            <li><a href="#">#mama</a></li>

            <li><a href="#">#papa</a></li>

            <li><a href="#">#ape</a></li>



            <li><a href="#">Separated link</a></li>



            <li><a href="#">One more separated link</a></li>

          </ul>

  </div>

</div>

app/views/common/_login.html.erb
 <% if !current_user %>
         <li> <%= link_to("註冊", new_user_registration_path) %> </li>
         <li> <%= link_to("登入", new_user_session_path) %> </li>
       <% else %>
         <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Hi!, <%= current_user.email %>
             <b class="caret"></b>
           </a>
           <ul class="dropdown-menu">
        	 <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
		 <li> <%= link_to("account info",edit_user_registration_path)%></li> 
		  <li> <%= link_to("My Posts", account_posts_path) %></li> 
	           <li> <%= link_to("My Responds", account_responds_path) %></li> 
           </ul>
         </li>
       <% end %>

app/views/common/_sponsor.html.erb
 <div class="panel panel-default">

  <div class="panel-body">

   © 2015 Twitter

   © 2015 Twitterv

   © 2015 Twitter

   © 2015 Twitter

   v

   © 2015 Twitterv

   v

   © 2015 Twitter

   vv© 2015 Twitter

  </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Xmas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>

<!-- HTML5 Hello world by kirupa - http://www.kirupa.com/html5/getting_your_feet_wet_html5_pg1.htm -->

<html lang="en-us">

<head>
  <%= render "common/header" %> 
 </head>

<body background="http://www.17sucai.com/upload/55/2013-05-18/9d9dfa45e36a128f97889a9088be4ce6_big">

<script src="https://code.jquery.com/jquery-1.11.3.js"></script>

<script src="js/bootstrap.js"></script>

<script src="twitter.js"></script>



<nav class="navbar navbar-default">

  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

        <span class="sr-only">Toggle navigation</span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>

      </button>

      <a class="navbar-brand" href="#">Twitter</a>

    </div>



    <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">

        <li class="active"><a href="#">    <i class="fa fa-home"></i>主頁<span class="sr-only">(current)</span></a></li>

        <li><a href="#"><i class="fa fa-bell"></i>通知</a></li>

        <li><a href="#"><i class="fa fa-newspaper-o"></i>訊息</a></li>

      </ul>

     

      <ul class="nav navbar-nav navbar-right">

        <form class="navbar-form navbar-left" role="search">

         <div class="form-group" >

          <input align=right type="text" class="form-control" placeholder="搜尋 Twwitter">

         </div>

         <button type="submit" class="btn btn-default">Submit</button>

        </form>

	<%=render"common/login"%>

       <li><!-- Button trigger modal -->

<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">

  <i class="fa fa-pencil-square-o"></i>

</button>



<!-- Modal -->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

  <div class="modal-dialog" role="document">

    <div class="modal-content">

     <%= simple_form_for @post do |f|%>
      <div class="modal-header">

        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

        <h4 class="modal-title" id="myModalLabel">NEW TWEET</h4>

      </div>
      <div class="modal-body">
 	<%= f.input :description,input_html: {class: "form-control"}%>
       <!--<div class="input-group">
 	<input type="text" class="form-control"placeholder="type something!" aria-describedby="basic-addon1">
	</div>
      </div>-->

      <div class="modal-footer">

        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<%=f.submit"TWEET!" , class: "btn btn-primary", data:{disable_with: "BIRD FLYING.."}%>
        <!--<button type="button" class="btn btn-primary">Save changes</button>-->
	<%end%>
      </div>

    </div>

  </div>

</div></li>
      </ul>

    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->

</nav>





<!--usercardboard-->

<div class="row">
	<div class="col-md-3">
		<div class="panel panel-primary">
			<% if current_user %>
  			 <div class="panel-heading"> 
        			<img class="img-size" src = "https://scontent-tpe1-1.xx.fbcdn.net/hphotos-frc3/v/t1.0-9/1902737_733335580072245_47296372
				02895015257_n.jpg?oh=2a083331b7d17ad9c6997b69a3c6408a&oe=56F2343B" height="300" width="300" />
    			    <h1><%=current_user.name%></h1>
     			   <p><%=current_user.email%></p>
  			 </div> 
			<%end%>
         	<div class="panel-body"> 
        	 <ul class="photo-profile">
            		<div class="row">
            		<div class="col-md-6">  推文  </div>

         		<div class="col-md-6"> 關注  </div>
         		</div>

			<% if current_user %>
         		 <div class="row">
        	   		<div class="col-md-6"><%= current_user.posts.size %></div>
            			<div class="col-md-6">1 </div>
            		</div>
			<%end%>
			
        	 </ul> 
  		</div>

	 	 </div>

 	</div>



<!--events-->

 <div class="col-md-6">
    <div class="panel panel-default">
    	<div class="panel-body">
	 <div class="row">
		 <div class="col-md-1">           
		   <span class="input-group-addon" id="basic-addon1"><i class="fa fa-twitter"></i></span>
		</div>

		<div class="col-md-8">
			<ul class="container">
			<li>
				 <button type="button" class="btn btn-default" data-toggle="collapse" 
					data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample" style="width:500px">
				 		有什麼新的事物<span class="input-group-addon"><i class="fa fa-camera"></i></span>
				 </button>
				    <div class="collapse" id="collapseExample">
				       <div class="input-group">
					       <input type="text" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
				       </div>
					      <p>媒體</p>
				    </div>

				</div>
			</li>
			<li>
<!--events-->
			<div class="row">
					<div class ="col-md-10">
					<% @posts.each do |post|%>
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title"><%= link_to(post.user_id , post_path(post))%></h3>
								<%if post.editable_by?(current_user)%>
									 <%= link_to("Edit", edit_post_path(post), class: "btn btn-sm pull-right")%>
									<%= link_to("Delete", post_path(post),    class: "btn btn-sm pull-right",
									  method: :delete, data: { confirm: "Are you sure?" } )%>
								<%end%>
							</div>
							<div class="panel-body">
								<%= post.description%>
								
							</div>
						</div>
						<div class= "jumbotron">
							<%@responds.each do |respond|%>
							<div class ="panel panel-default">
								<div class ="panel-body">
								 <%= respond.content %>
								 <%if post.editable_by?(current_user)%>
								 <%= link_to("Edit", edit_respond_path(respond), class: "btn btn-sm pull-right")%>
								 <%= link_to("Delete", respond_path(respond),    class: "btn btn-sm pull-right",
											method: :delete, data: { confirm: "Are you sure?" } )%>
								<%end%>
                                
								</div>
							</div>
							<%end%>
		  
				<%end%>
					</div>
				 </div>
		</div>

			</li>
			</ul>
	  </div>
     	</div>
    </div>
 </div>

		  <div class="col-md-3">
              	  <%=render "common/sponsor" %>     
		  </div>

</div>
<!--events-->





<div class="row">

<div class="col-md-3">
 <%= render "common/hot" %>
</div>

</div>









</body>



</html>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en-us">
<head>
        <%= render "common/header"%>
</head>

<body bgcolor= "gray">
 <div class="row" style="margin:40px"> 
          <div class="col-md-11" style="display:block;margin:auto" >
            <div class="jumbotron" style="display:block;margin:auto, margin-top:0px"  >
                        <div class="panel panel-primary">
                             <div class="panel panel-heading">
                              <h2><%= @post.user_id %></h2>
                             </div>
                             <div class="panel-body">
                              <p><%= @post.description %></p>
                              <p> <%= link_to("Edit", edit_post_path(@post), class: "btn btn-primary pull-right")%>
                                 <%= link_to("Delete", post_path(@post), class: "btn btn-primary pull-right", method: :delete)%></p>
                             </div>
                        </div>
             
	 	
		 <div class="alert alert-info" role="alert">
		
		</div>
	     </div>
         </div>
</body>